### ISSUE TITLE
There is no data for USA in processed/coronavirus.csv file

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/data#1]
Is this an issue of the data source or because of the processing script?

**Comment by pat-s** [comment]
The US data is in a separate file, see https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series. 
The file is currently not downloaded and processed.

**Comment by dsbb-finddx** [comment]
Is it possible to download and process US data in your scripts of the R package?

**Comment by pat-s** [comment]
Sure, it just needs to be joined to the other DF that uses the non-US data after downloading.

Here:

https://github.com/dsbbfinddx/FIND_Cov_19_Tracker/blob/f554fab441de3f497f51049a87d703bace7d76a8/R/case-data.R#L13-L15

**Comment by dsbb-finddx** [comment]
Could you please add the code to implement this?

**Comment by pat-s** [comment]
I've added the US data and bound the observations to the already existing ones.

However, USA is dropped before writing because mapping data (from `countries_codes_and_coordinates.csv`) is lacking for the USA.

**Comment by dsbb-finddx** [comment]
US data for cases are found here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

There is no need to add them separately.
In the current app we were using the jhuID from the countries_codes_and_coordinates.csv
The correct file to be used is:

https://raw.githubusercontent.com/dsbbfinddx/FIND_Cov_19_Tracker/master/input_data/countries_codes_and_coordinates.csv

I think this would result in fewer countries to be dropped.

**Comment by christophsax** [comment]
If we had into data or other problems, the best thing is to greate a
reproducible example, or reprex. The
[article](https://reprex.tidyverse.org/articles/articles/magic-reprex.html)
explains what a reprex is and why it is one of the most important yet most
underrated things in R.

Here is a reprex for the (still) missing US data. It may be because the run has not been completed, will try to do it manually in a second and update if successful.
But this is good to see why reprexes are helpful.

``` r
library(tidyverse)
data_shiny_url <- "https://raw.githubusercontent.com/dsbbfinddx/data/master/processed/data_shiny.csv"
data_shiny <- as_tibble(read.csv(data_shiny_url))

# US still has no data
data_shiny %>% 
  filter(country == "US")
#> # A tibble: 0 x 9
#> # … with 9 variables: country <chr>, date <chr>, cases <int>, new_cases <int>,
#> #   deaths <int>, new_deaths <int>, tests <int>, new_tests <int>,
#> #   pop_100k <dbl>

# If we think something is wrong in a particular series, it automatically 
# generates and uploads a plot - pure magic!
data_shiny %>% 
  filter(country == "CH") %>% 
  select(date, cases) %>% 
  tsbox::ts_plot()
#> [time]: 'date' [value]: 'cases'
```

![](https://i.imgur.com/Pn7KMZE.png)

<sup>Created on 2020-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Apparently multiple files named `countries_codes_and_coordinates.csv` were present in the repo(s).

``` r
library(tidyverse)
file1 = suppressWarnings(readr::read_csv("https://raw.githubusercontent.com/dsbbfinddx/data/master/raw/countries_codes_and_coordinates.csv",
                                         col_types = readr::cols()
))

file2 = suppressWarnings(readr::read_csv("https://raw.githubusercontent.com/dsbbfinddx/FIND_Cov_19_Tracker/master/input_data/countries_codes_and_coordinates.csv",
                                         col_types = readr::cols()
))

all.equal(file1, file2)
#>  [1] "Names: 1 string mismatch"                                                        
#>  [2] "Attributes: < Component \"row.names\": Numeric: lengths (258, 263) differ >"     
#>  [3] "Attributes: < Component \"spec\": Component \"cols\": Names: 1 string mismatch >"
#>  [4] "Component \"X1\": Numeric: lengths (258, 263) differ"                            
#>  [5] "Component \"country\": Lengths (258, 263) differ (string compare on first 258)"  
#>  [6] "Component \"country\": 10 string mismatches"                                     
#>  [7] "Component \"alpha2\": Lengths (258, 263) differ (string compare on first 258)"   
#>  [8] "Component \"alpha3\": Lengths (258, 263) differ (string compare on first 258)"   
#>  [9] "Component \"numeric\": Numeric: lengths (258, 263) differ"                       
#> [10] "Component \"latitude\": Numeric: lengths (258, 263) differ"                      
#> [11] "Component \"longitude\": Numeric: lengths (258, 263) differ"                     
#> [12] "Component \"penalty\": Numeric: lengths (258, 263) differ"                       
#> [13] "Component \"population\": Numeric: lengths (258, 263) differ"                    
#> [14] "Component 10: Lengths (258, 263) differ (string compare on first 258)"           
#> [15] "Component 10: 15 string mismatches"                                              
#> [16] "Component \"notes\": Lengths (258, 263) differ (string compare on first 258)"
```

<sup>Created on 2020-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In the one that is still in the `input_data` directory there is an entry for the US and hence the US data is not dropped. 
I've updated the file that is being used in the R package now. At 6 pm, the US should be in `data_shiny.csv` then.

**Comment by dsbb-finddx** [comment]
Thank you for the reprex, Patrick. 
US data are found here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
So, I wanted to make sure you retrieve them from time_series_covid19_confirmed_global.csv and not from the time_series_covid19_confirmed_US.csv as you do here:

https://github.com/dsbbfinddx/FIND_Cov_19_Tracker/blob/r-package/R/case-data.R

**Comment by pat-s** [comment]
> So, I wanted to make sure you retrieve them from time_series_covid19_confirmed_global.csv and not from the time_series_covid19_confirmed_US.csv as you do here:

I've already reverted again, only `confirmed_global.csv` is used. (Even though the data should be identical probably?).

**Comment by pat-s** [comment]
USA should be in now, let me know if something is not working as expected.

**Comment by christophsax** [comment]
Yes, still not here (my reprex above is a good way to check).

``` r
library(tidyverse)
data_shiny_url <- "https://raw.githubusercontent.com/dsbbfinddx/data/master/processed/data_shiny.csv"
data_shiny <- as_tibble(read.csv(data_shiny_url))

# US still has no data
data_shiny %>% 
  filter(country == "US")
#> # A tibble: 0 x 9
#> # … with 9 variables: country <chr>, date <chr>, cases <int>, new_cases <int>,
#> #   deaths <int>, new_deaths <int>, tests <int>, new_tests <int>,
#> #   pop_100k <dbl>
```

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
The identifier is "USA" not "US".

**Comment by pat-s** [comment]
OK in now

``` r
library(tidyverse)
data_shiny_url <- "https://raw.githubusercontent.com/dsbbfinddx/data/master/processed/data_shiny.csv"
data_shiny <- as_tibble(read.csv(data_shiny_url))

# US still has no data
data_shiny %>% 
  filter(country == "US")
#> # A tibble: 169 x 9
#>    country date       cases new_cases deaths new_deaths tests new_tests pop_100k
#>    <chr>   <chr>      <int>     <int>  <int>      <int> <int>     <int>    <dbl>
#>  1 US      2020-01-22     1        NA      0         NA    NA        NA       NA
#>  2 US      2020-01-23     1         0      0          0    NA        NA       NA
#>  3 US      2020-01-24     2         1      0          0    NA        NA       NA
#>  4 US      2020-01-25     2         0      0          0    NA        NA       NA
#>  5 US      2020-01-26     5         3      0          0    NA        NA       NA
#>  6 US      2020-01-27     5         0      0          0    NA        NA       NA
#>  7 US      2020-01-28     5         0      0          0    NA        NA       NA
#>  8 US      2020-01-29     5         0      0          0    NA        NA       NA
#>  9 US      2020-01-30     5         0      0          0    NA        NA       NA
#> 10 US      2020-01-31     7         2      0          0    NA        NA       NA
#> # … with 159 more rows
```

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by christophsax** [comment]
Thanks. It's also picked up by the app:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/1390827/87033238-2411b300-c1e6-11ea-9a31-3b0d7b355b55.png">


Another problem is that we have no `pop_100k` for the US. @dsbb-finddx Any idea why not?

**Comment by pat-s** [comment]
Because the same naming problem (spaces/no spaces) occurs when joining the population data. I'll fix it.

**Comment by pat-s** [comment]
Updated the population data country names. The following are definitely missing though:

```r
ℹ `process_jhu_data()`: Population data lacking for the following countries: Burma,
  DiamondPrincessCruiseShip, Kosovo, and MSZaandam.
```
